include:
  - board: nice_nano_v2
    shield: slaet_left
  - board: nice_nano_v2
    shield: slaet_right
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right