manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/JordanNiphan/
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    west-commands: scripts/west-commands.yml
    path: config