manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/JordanNiphan/
  projects:
    - name: SlaetZmk
      remote: zmkfirmware
      revision: main
      import: SlaetZmk/app/west.yml
  self:
    path: config