manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/JordanNiphan
  projects:
    - name: zmk-config-Slaet
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
